#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

echo_error() {
  echo "Error:" "$@" 1>&2
}

test_commands() {
  local flags=$-
  local exit=false
  if [[ $flags =~ e ]]; then set +e; fi # disable exit on error
  # for each argument
  while [[ $# -gt 0 ]]; do
    # check that command is defined
    if [ ! -x "$(command -v "$1")" ]; then
      echo_error "The required program \"$1\" is not installed"
      exit=true
    fi
    shift
  done
  if [[ $flags =~ e ]]; then set -e; fi # re-enable exit on error
  if $exit; then exit 1; fi
}

test_env_variables() {
  local flags=$-
  local exit=false
  if [[ $flags =~ u ]]; then set +u; fi # disable exit on undefined variables
  # for each argument
  while [[ $# -gt 0 ]]; do
    # check that env variable is defined
    if [ -z "${!1}" ]; then
      echo_error "The required environment variable \"$1\" is not defined"
      exit=true
    fi
    shift
  done
  if [[ $flags =~ u ]]; then set -u; fi # re-enable exit on undefined variables
  if $exit; then exit 1; fi
}

script_stage_secrets() {
  :
}

script_deploy_secrets() {
  :
}

script_deploy_webserver() {
  :
}

script_deploy_database() {
  :
}

script_deploy_help() {
  echo "Start the app locally."
  echo
  echo "Usage:"
  echo "  nix run .#deploy             | Alias for \"nix run .#deploy help\""
  echo "  nix run .#deploy [SCRIPT]... | Run the specified scripts"
  echo
  echo "SCRIPTS:"
  echo "  help --help -h      | Print this helpful information"
  echo "  database postgres   | Deploy the Postgres database and its schema to Fly"
  echo "  webserver sveltekit | Deploy the Node webserver generated by SvelteKit to Fly"
  echo "  secrets             | Deploy the secrets to Fly"
  echo "  all                 | Deploy the entire website to Fly"
  echo
}

scripts=()
script_args=()
interpret_script() {
  # if no arguments passed, run the default script
  if [[ $# -eq 0 ]]; then
    scripts+=("script_deploy_help")
    return;
  fi
  # otherwise run the scripts specified by arguments, until an option is encountered that is not recognized as a script
  while [[ $# -gt 0 ]]; do
    case $1 in
      help|--help|-h)
        scripts=("script_deploy_help")
        return;
      ;;
      database|postgres)
        scripts+=("script_deploy_database")
      ;;
      webserver|sveltekit)
        scripts+=("script_deploy_webserver")
      ;;
      secrets)
        scripts+=("script_deploy_secrets")
      ;;
      all)
        scripts+=("script_deploy_all")
      ;;
      *)
        break
      ;;
    esac
    shift
  done
  # if no script was identified, print an error
  if [[ -z "${scripts[*]}" ]]; then
    echo_error "The argument \"$1\" is not a recognized script"
    echo_error "Try \"help\" to show available scripts"
    exit 1
  fi
  # remaining 
  script_args+=("$@")
}

go_to_base_directory() {
  test_commands git
  # if current directory is not a git directory, return
  if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    return
  fi
  # go to the base of the git directory
  cd "$(git rev-parse --show-toplevel)"
}

load_env_files() {
  # go to base directory
  go_to_base_directory
  # for each file
  while [[ $# -gt 0 ]]; do
    # if file isn't readable, continue
    if [ ! -r "$1" ]; then
      shift
      continue
    fi
    # load file
    set -a
    # shellcheck disable=SC1091 source=/dev/null
    source "$1"
    set +a
    shift
  done
  # return to last directory
  cd - > /dev/null
}

main() {
  : "${ENV_FILE:=".env"}"
  load_env_files "$ENV_FILE"
  interpret_script "$@"
  for script in "${scripts[@]}"; do
    "$script" "${script_args[@]}"
  done
}

main "$@"
